---
- hosts: zabbix
  become: yes
  roles:
  - setlocalrepo
  - { role: apache2, action: 'virtualhost', zabbix_config: 'yes', vhost_name: 'zabbix', vhost_dir: '/usr/share/zabbix' }
  - { role: mysql }
  - { role: zabbixserver }
  - { role: zabbixserver, action: 'zabbixcreatedb' }

- hosts: zabbix
  become: yes
  roles:
  - { role: zabbixserver, action: 'zabbixcreategroup', zabbix_groups_for_create: "{{ groups.keys() }}" }
  - { role: zabbixserver, action: 'installpy' }
- hosts: repository
  become: yes
  roles:
  - { role: zabbixagent, action: 'zabbixcreatehost', host_group: "{{ group_names }}" } #{{ zabbx_host_groups }} }

